/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:35cad19b-bd9c-47bd-9530-900150a1b397',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_Yz6b4ktsV',
  aws_user_pools_web_client_id: '2d9nfgsm8l5k4n9el37bpgr5bv',
  oauth: {},
  aws_cloud_logic_custom: [
    {
      name: 'AdminQueries',
      endpoint: 'https://a04ei50df2.execute-api.eu-west-1.amazonaws.com/dev',
      region: 'eu-west-1',
    },
  ],
  aws_appsync_graphqlEndpoint:
    'https://sa2hvdvqbjdxlnzgpkiiy24kpa.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-west-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile
